### ISSUE TITLE
[TCP]: Refactor SockAddr in Settings

### ISSUE THREAD

**Issue by LeMarwin** [hexresearch/ergvein#627]
Right now we store raw SockAddr in settings, which is ugly and was only done as a temporary thing.

Store either text url or an object like 
``` yaml
activeSockAddrs: 
- tag: HostPort
  host: 127.0.0.1
  port: 123
- indexerurl.biz
```
